name: Run Google Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # This adds a "Run workflow" button in the GitHub UI
  
jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build solution
      run: msbuild my_project.sln

    - name: Run tests
      run: |
        .\run_tests.exe --gtest_output=xml:report.xml

    - name: Upload XML artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.xml
