name: Run Google Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Google Test
      shell: cmd
      run: vcpkg install gtest:x64-mingw-dynamic

    - name: Build and Test
      shell: cmd
      run: |
        :: Set environment for the Makefile
        set VCPKG_ROOT=C:/vcpkg
        
        :: Add the vcpkg BIN folder to PATH (Important so the .exe can find gtest.dll)
        set PATH=C:\vcpkg\installed\x64-mingw-dynamic\bin;%PATH%
        
        :: Run the build
        mingw32-make test
